name = "PiccoloMultidocs"
uuid = "46b20c90-705b-4343-b51e-eec7e31cee4a"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MultiDocumenter = "87ed4bf0-c935-4a67-83c3-2a03bee4197c"
