name: Rebuild Docs from Dispatch
on:
  repository_dispatch:
    types: [rebuild-docs]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # Ensure we are on the main branch of PiccoloMultiDocs.jl
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Rebuild and Deploy Docs
        run: |
          TODAY_DATE=$(date +%Y-%m-%d)
          git config user.name github-actions
          git config user.email github-actions@github.com
          julia --project=docs docs/make.jl deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
