name: Rebuild Docs from Dispatch
on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild-docs]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Build documentation
        run: julia --project=docs docs/make.jl
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          publish_dir: ./docs/out
          cname: docs.harmoniqs.co